apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: apr4-testnewgitops-llamacpp-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr4-testnewgitops-llamacpp-3
  name: apr4-testnewgitops-llamacpp-3
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apr4-testnewgitops-llamacpp-3
    weight: 100
  wildcardPolicy: None
