apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: apr4-testnewgitops-llamacpp-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/apr4-testnewgitops-llamacpp-3:008a1c3246cf98910467abbff3bfed4e60a5f417@sha256:5a80a775000dbda3c35103d52907b453329ea76b509ff8d2f5ef068c21c6158a # use pre-built to bootstrap
          name: app-inference
